// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuRy6vajdKHcCq4RATH4L9ibED1qlXGas',
    appId: '1:498404230995:web:be5f6dc4dcb970f6d643a6',
    messagingSenderId: '498404230995',
    projectId: 'beauty-parlor-app-88b3d',
    authDomain: 'beauty-parlor-app-88b3d.firebaseapp.com',
    storageBucket: 'beauty-parlor-app-88b3d.firebasestorage.app',
    measurementId: 'G-85SYYYWLX8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIqwg_nMB29zDu4duhxIf7PBK_brKp6a4',
    appId: '1:498404230995:android:0efc266f67e65eecd643a6',
    messagingSenderId: '498404230995',
    projectId: 'beauty-parlor-app-88b3d',
    storageBucket: 'beauty-parlor-app-88b3d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnFuGASWGWY_t2hui1C-DCC1IjWTH0rgo',
    appId: '1:498404230995:ios:d808da5cd194b0e4d643a6',
    messagingSenderId: '498404230995',
    projectId: 'beauty-parlor-app-88b3d',
    storageBucket: 'beauty-parlor-app-88b3d.firebasestorage.app',
    androidClientId: '498404230995-chc8hboa4bpfrchjhll8m7o8m166ug67.apps.googleusercontent.com',
    iosClientId: '498404230995-bo9tuafljb11b4rn0u4d9uta0nblfhbv.apps.googleusercontent.com',
    iosBundleId: 'com.example.parlorVendorApp',
  );
}
